spring:
  profiles:
    active: ${SCOPE}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    file:
      upload-dir: ./uploads
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        format_sql: true
        show_sql: true
        use_sql_comments: true
app:
  datasource:
    primary:
      jdbcUrl: jdbc:mysql://${DB_LOCAL_URL:localhost:3306}/optimalstandard?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT-4&useUnicode=yes&characterEncoding=UTF-8
      username: ${LOCAL_DB_USER}
      password: ${LOCAL_DB_PASS}
      maximum-pool-size: 3