insert into application_area (name, deleted)
values ('Muros de contención - Presión positiva sin napa ', false),
       ('Muros de contención - Presión positiva con napa - c/tratamiento de juntas frías', false),
       ('Muros de contención - Presión negativa sin napa', false),
       ('Muros de contención - Presión negativa con napa - c/tratamiento de juntas frías', false),
       ('Terrazas transitables c/ carpeta de protección ', false),
       ('Terrazas transitables s/ carpeta de protección', false),
       ('Terrazas transitables con alta deformabilidad ', false),
       ('Cubiertas no transitables s/ protección', false),
       ('Cubiertas no transitables s/ protección', false),
       ('Cubiertas no transitables invertidas c/ placas ATR y carga pesada', false),
       ('Cubiertas no transitables invertidas c/ placas ATR y carga pesada', false),
       ('Cubiertas transitables c/ carpeta de protección', false),
       ('Cubiertas transitables c/ carpeta de protección', false),
       ('Sobre paramentos int/ext bajo revoque ext.: mamp. Cerámicos', false),
       ('Sobre paramentos int/ext bajo revoque ext: bloques HCCA', false),
       ('Sobre paramentos int/ext bajo revoque ext: hormigón', false),
       ('Sobre paramentos int/ext tipo trepante hgón: cara interior', false),
       ('Sobre paramentos int/ext tipo trepante hgón: cara exterior', false),
       ('Tanques de agua potable (cara interior)', false),
       ('Pozos de bombeo aguas servidas c/ presión negativa', false),
       ('Fosos de ascensor c/ presión negativa', false),
       ('Piscinas', false),
       ('Baños c/ tabiquería drywall, bajo revestimiento', false),
       ('Baños c/ tabiquería tradicional, bajo revestimiento', false);
